name: C/C++ CI

on:
  push:
    branches: [ dev_GitHub_CI ]

jobs:
  build:

    runs-on: debian

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: uname -a ; apt-get update -qq ; apt-get install -y  openscad ; which openscad | tee which_openscad.txt ; openscad --version 2>&1 | tee openscad_version.txt

