name: C/C++ CI

on:
  push:
    branches: [ dev_GitHub_CI ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: installs
      run: sudo apt-get update -qq ; sudo apt-get install -y blender

    - uses: actions/checkout@v2
    - name: versions
      run: uname -a ;
        make --version ;
        which blender | tee which_blender.txt ;
        blender --version 2>&1 | tee blender_version.txt ;

    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: which_blender.txt,
          blender_version.txt,

