name: C/C++ CI

on:
  push:
    branches: [ dev_GitHub_CI ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install xmllint
      run: sudo apt-get update -qq ; sudo apt-get install -y  openscad

    - uses: actions/checkout@v2
    - name: make
      run: uname -a ; make --version ; which openscad | tee which_openscad.txt ; openscad --version 2>&1 | tee openscad_version.txt

